name: Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          MONGODB_HOST: localhost
          MONGODB_PORT: 27017
